package org.ourapp.udada.food;

import lombok.Data;

@Data
public class FoodDTO {
	
	
	/*
		F_NO	VARCHAR2(20 BYTE)
		F_NAME	VARCHAR2(1000 BYTE)
		F_REGION	VARCHAR2(500 BYTE)
		F_MJCLASS	VARCHAR2(500 BYTE)
		F_MNCLASS	VARCHAR2(500 BYTE)
		F_ONCEOFFER	NUMBER
		F_MEASURE	VARCHAR2(10 BYTE)
		F_OFFERG	NUMBER
		F_OFFERML	NUMBER
		F_KCAL	NUMBER
		F_PROTEIN	NUMBER
		F_FAT	NUMBER
		F_CARBO	NUMBER
		F_SUGAR	NUMBER
		F_FIBER	NUMBER
		F_NA	NUMBER
		F_CHOLES	NUMBER
		F_DIV	VARCHAR2(30 BYTE)
	 * 
	 * */

	
	
}
